OLLAMA_BASE         = "http://127.0.0.1:11434"
OLLAMA_URL          = f"{OLLAMA_BASE}/api/chat"
OLLAMA_GENERATE_URL = f"{OLLAMA_BASE}/api/generate"
MODEL               = r"llama3.2:3b"
FILES_DIR           = r"D:\Jarvis-Workspace\files"
CACHE_DIR           = r"D:\Jarvis-Workspace\cache"
SMART_READ_DIR      = r"D:\Jarvis-Workspace\smart_read"
MEMORY_FILE         = r"D:\Jarvis-Workspace\memory.json"
OLLAMA_PATH         = r"C:\Users\Mathesh chand\AppData\Local\Programs\Ollama\ollama.exe"
TIMEOUT             = 120   
STREAM_TIMEOUT      = 300   
POPPLER_PATH        = r"C:\poppler-26.02.0-0\poppler-26.02.0\Library\bin"
TESSERACT_PATH      = r"C:\Program Files\Tesseract-OCR\tesseract.exe"